/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DeliveriesRouteImport } from './routes/deliveries'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as StockRouteImport } from './routes/stock'
import { Route as CustomersIndexRouteImport } from './routes/customers.index'
import { Route as CustomersIdRouteImport } from './routes/customers.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveriesRoute = DeliveriesRouteImport.update({
  id: '/deliveries',
  path: '/deliveries',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const StockRoute = StockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersIndexRoute = CustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersIdRoute = CustomersIdRouteImport.update({
  id: '/customers/$id',
  path: '/customers/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/deliveries': typeof DeliveriesRoute
  '/payments': typeof PaymentsRoute
  '/products': typeof ProductsRoute
  '/reports': typeof ReportsRoute
  '/setup': typeof SetupRoute
  '/stock': typeof StockRoute
  '/customers/$id': typeof CustomersIdRoute
  '/customers/': typeof CustomersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/deliveries': typeof DeliveriesRoute
  '/payments': typeof PaymentsRoute
  '/products': typeof ProductsRoute
  '/reports': typeof ReportsRoute
  '/setup': typeof SetupRoute
  '/stock': typeof StockRoute
  '/customers/$id': typeof CustomersIdRoute
  '/customers': typeof CustomersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/deliveries': typeof DeliveriesRoute
  '/payments': typeof PaymentsRoute
  '/products': typeof ProductsRoute
  '/reports': typeof ReportsRoute
  '/setup': typeof SetupRoute
  '/stock': typeof StockRoute
  '/customers/$id': typeof CustomersIdRoute
  '/customers/': typeof CustomersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/deliveries'
    | '/payments'
    | '/products'
    | '/reports'
    | '/setup'
    | '/stock'
    | '/customers/$id'
    | '/customers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/deliveries'
    | '/payments'
    | '/products'
    | '/reports'
    | '/setup'
    | '/stock'
    | '/customers/$id'
    | '/customers'
  id:
    | '__root__'
    | '/'
    | '/deliveries'
    | '/payments'
    | '/products'
    | '/reports'
    | '/setup'
    | '/stock'
    | '/customers/$id'
    | '/customers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DeliveriesRoute: typeof DeliveriesRoute
  PaymentsRoute: typeof PaymentsRoute
  ProductsRoute: typeof ProductsRoute
  ReportsRoute: typeof ReportsRoute
  SetupRoute: typeof SetupRoute
  StockRoute: typeof StockRoute
  CustomersIdRoute: typeof CustomersIdRoute
  CustomersIndexRoute: typeof CustomersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deliveries': {
      id: '/deliveries'
      path: '/deliveries'
      fullPath: '/deliveries'
      preLoaderRoute: typeof DeliveriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock': {
      id: '/stock'
      path: '/stock'
      fullPath: '/stock'
      preLoaderRoute: typeof StockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/': {
      id: '/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof CustomersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/$id': {
      id: '/customers/$id'
      path: '/customers/$id'
      fullPath: '/customers/$id'
      preLoaderRoute: typeof CustomersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DeliveriesRoute: DeliveriesRoute,
  PaymentsRoute: PaymentsRoute,
  ProductsRoute: ProductsRoute,
  ReportsRoute: ReportsRoute,
  SetupRoute: SetupRoute,
  StockRoute: StockRoute,
  CustomersIdRoute: CustomersIdRoute,
  CustomersIndexRoute: CustomersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
